spring:
  datasource:
    url: postgres://ihxrsopk:xA7dsvddVv80Q7E1tdudLRW1lJQFyUIq@rain.db.elephantsql.com/ihxrsopk
    username: ihxrsopk
    password: xA7dsvddVv80Q7E1tdudLRW1lJQFyUIq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
